name: BDD Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.8-slim

    # Required services    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl wget python3-selenium
      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Run the server locally
        run: |
          echo "\n*** STARTING APPLICATION ***\n"
          gunicorn --log-level=critical --bind=0.0.0.0:5000 service:app &
          sleep 5
          curl -I http://localhost:5000/
          echo "\n*** SERVER IS RUNNING ***"
        env:
          DATABASE_URI: postgres://postgres:postgres@postgres:5432/postgres_db
      - name: Upload coverage report to codecov.io
        uses: codecov/codecov-action@v2 
      - name: Run BDD tests with behave
        run: behave
